#! /bin/bash


OPTION=$(whiptail --title "Applications html" --backtitle "Lanceur d'appli html" --menu "Choisissez une option :" 15 60 4 \
"1" "DIY e-liquide" \
"2" "Option 2" \
3>&1 1>&2 2>&3)

# exitstatus et renvoyé par whiptail : 0 correspond au choix d'une option, 1 à l'annulation du choix
exitstatus=$?
if [ $exitstatus = 0 ]; then
    if [ $OPTION = 1 ]; then
        echo "DIY e-liquide"
    # code a executer
    xdg-open ~/bin/html/DIY_eliquide.html

    elif [ $OPTION = 2 ]; then
        echo "====== Option 2 ======"
    # code a executer
    fi
else
    echo "Action annulée"
fi

kill $$
