#! /usr/bin/env python3
# -*- coding : utf-8 -*-

import string
from random import choice
from sys import argv

if len(argv) > 1:

    try:
        nombre = int(argv[1])
        message = ''
    except AssertionError:
        message = ">[Le nombre doit être un entier positif]<\n"
    except:
        message = ">[L'argument attendu est un entier positif]<\n"
    print(message)


if len(argv) > 1:
    nbre = int(argv[1])
else:
    nbre = 50


def sk_gen(nbre):
    # alphabet = string.ascii_letters + string.digits + string.printable
    alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#%&()*+-/?@_~'
    password = ''.join(choice(alphabet) for i in range(nbre))
    return print(password)


sk_gen(nbre)
